### ISSUE TITLE
Configuration of CASHREF parameter in issuer-ressource 

### ISSUE THREAD

**Issue by grindsa** [nokia/ncm-issuer#17]
I find the configuration of the CASHREF parameter a bid convoluted and not really intuitive. Don't you think it would be better to combine ngServer and CASHREF parameter into a single configuration option in which you set the full URI given by NCM?

So something like:

```
spec:
   secretName: SECRET_NAME_WITH_REST_CREDS
   tlsSecretName: SECRET_NAME_WITH_TLS_CERT
   CASHREF: https://foo.bar.local:8084/v1/certificates/p4adf83c378c4dsase3
```
